spring:
  application:
    name: BlogSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bricks_blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 111111

server:
  servlet:
    context-path: /
  port: 8080

mybatis:
  mapper-locations: classpath*:mappers/*.xml
