.PHONY: clean All

All:
	@echo "==========Building project:[ C++ - Release ]=========="
	@cd "C++" && "$(MAKE)" -f  "C++.mk"
clean:
	@echo "==========Cleaning project:[ C++ - Release ]----------"
	@cd "C++" && "$(MAKE)" -f  "C++.mk" clean
